### ISSUE TITLE
budget amount

### ISSUE THREAD

**Issue by shamsu203** [jerrymjones/MonthlyBudgetEditor#4]
I am using the old style udget in moneydance. I recently downloaded you monthly budget editor. My monthly budgeted value is the same for each month. how do I copy the values badugeted for one mo th to other periods 
Tks 
Shamsu

**Comment by jerrymjones** [comment]
Shamsu,

Go to the cell you want to copy the budgeted value for and **right click** on it to bring up a popup menu for special operations you can perform on the cell. Select **Apply selected cell to end of year** or **Apply selected cell to entire year** as desired.

**Comment by shamsu203** [comment]
Jerry
Tks for your help. It worked

**Comment by jerrymjones** [comment]
No problem.

Jerry
