### ISSUE TITLE
Text color 

### ISSUE THREAD

**Issue by droland49** [jerrymjones/MonthlyBudgetEditor#9]
Hi Jerry, 
I have started using your Budget Editor for Moneydance and find it quite useful.

However, I have one small issue that perhaps you can help me with.

I have Moneydance setup using light pastel colors and the text colors, (green and cyan), on Budget Editor are too light to see.
Is there any way to change the text colors to a darker shade to make them easier to see?
Thanks,
Dave

**Comment by jerrymjones** [comment]
Hi Dave,

I think I use the default Moneydance colors for that but let me look 
into it.

*Jerry*

**Comment by jerrymjones** [comment]
Dave,

A couple of additional questions. Are you using one of the default 
themes or is this a custom one? If default, which one?

I mostly use something called the defaultTextForeground in the app. If 
you are using a custom theme, can you try changing the second setting 
(Default Foreground) and see if that helps?

*Jerry*

**Comment by droland49** [comment]
I am using a custom theme, like I mentioned, it is a light pastel theme.

The “default Foreground” color is black, so that does not apply.

 

I reviewed the other colors shown on MD preferences that I thought applied to the colors in question and revised them, but did not change the appearance.

I will try one of the standard themes and see if that changes anything and will let you know.

 

Dave

**Comment by droland49** [comment]
Hi Jerry,

Just to update, I have tried several of the standard MD themes.

The “solarized Light” and “Classic” themes have the same light cyan color.

 

I have attached a screen shot showing a small section of the budget editor screen, this is the MD “classic” theme.

 

The “Flat Dark” theme shows the text in readable font colors.

 

 

I hope this helps.

Dave

**Comment by jerrymjones** [comment]
Dave,

I didn't get the screenshot, maybe you could send it again? Unfortunately, I use the Flat Dark theme so I didn't see this problem.  In the editor, are all rows too light to see or is it only some of them? I do have some rows that I force the color. The first row "Income-Expenses" is light blue and parent rows are cyan. Re-reading through this makes me think these are the problem rows and normal category rows are ok. Is that right?

Jerry

**Comment by droland49** [comment]
I have attached the screen shot again.

 

The problem rows are the “Income-Expenses” in light blue (not too bad) and especially the “Parent Rows” in cyan.

It appears that the forced row colors are the issue.

All other rows use a black font and are just fine.

 

The colors in the dark theme look fine, but if a lighter theme is chosen the light colors are too light to see clearly.

I’m sorry if I was not clear initially in describing the problem I was having.

 

Dave

**Comment by jerrymjones** [comment]
Got it! I'll make this a bug and figure out what to do to fix it.

**Comment by droland49** [comment]
Thank you Jerry.

 

Sorry for making more work for you.

 

Best Regards,

Dave

**Comment by jerrymjones** [comment]
No problem, I appreciate the feedback!

**Comment by jerrymjones** [comment]
Dave,

If possible can you test this version and see if it is better? I had to zip it to get it to upload here but the contents is budgeteditor.mxt.

[budgeteditor.zip](https://github.com/jerrymjones/MonthlyBudgetEditor/files/10894006/budgeteditor.zip)

Jerry

**Comment by droland49** [comment]
Hi Jerry,

I have attached 2 screenshots, one using “Classic” theme and the other my custom theme.

As you can see, the text color is much better.

 

Since your extension is so clean and well laid out, you may want to consider having all text the same throughout.

That would avoid any issues going forward with some other custom theme.

Just a thought however.

 

Thank you for the help on this, excellent job on this extension.

 

Regards,

Dave

**Comment by jerrymjones** [comment]
Thanks Dave for checking.

**Comment by droland49** [comment]
Hi Jerry,

One last thing, can you make the same changes to the “Monthly Budget Report” extension?

I have the same issue with the font colors on that as well.

Many Thanks,

Dave

**Comment by jerrymjones** [comment]
Yep, already did. I'll send out a formal release soon or if you want 
I'll send you a test release. By the way, the color I used for non-dark 
themes is the "Color to be used for text when report calls for 'Blue'" 
color. So it can be customized if desired.

*Jerry*
Message ID: 
***@***.***>

**Comment by droland49** [comment]
Thanks Jerry

I’ll wait for the formal release.

The customization option is a great idea.

Dave

**Comment by jerrymjones** [comment]
Closed in v2205.
